name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v5.0.0
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies
      run: npm install

    - name: "Building command"
      run: npm run build 
    - name: "Running Unit Tests"
      run: npm run test 

    - name: "Running Security Checks"
      run: npm audit --audit-level=moderate  

    - name: "Trivy Scan for Docker Image"
      uses: aquasecurity/trivy-action@master
      with:
         image-ref: my-nodejs-app:latest
         format: 'table'
         exit-code: '1'
         severity: 'CRITICAL,HIGH'
         ignore-unfixed: true
         vuln-type: 'os,library'

    - name: "Building Docker Image"
      run: docker build -t myapp .  

    - name: Save Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: .