name: Docker Image CI

on:
  workflow_run:
    workflows: [Terraform CI/CD]
    types:
      - completed

jobs:

  build-test & scan:
    name: Build, Test & Scans 
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: production 