name: Docker Image CD

on:
  workflow_run:
    workflows: [Docker Image CI]
    types:
      - completed

jobs:

  build:
    deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v5.0.0
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: "Building command"
      run: npm run build 
  
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}   
    - name: Push to Azure Container Registry
      run: |
        az acr login --name containerRegistry1
        docker tag my-nodejs-app:latest containerRegistry1.azurecr.io/my-nodejs-app:latest
        docker push containerRegistry1.azurecr.io/my-nodejs-app:latest  
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: T-web-app
        images: containerRegistry1.azurecr.io/my-nodejs-app:latest  
        slot-name: T-web-slot
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1A2B3C4D5E6F7G8H9I }}
        package: .
