name: Docker Image CD

on:
  workflow_run:
    workflows: [Docker Image CI]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v5.0.0
      with: