name: Docker Image CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Run unit tests
      run: npm run test

    - name: Run security audit
      run: npm audit --audit-level=moderate

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Parse ACR credentials
      id: acr
      run: |
          echo "username=$(echo '${{ secrets.ACR_CREDENTIALS }}' | jq -r .username)" >> $GITHUB_OUTPUT
          echo "password=$(echo '${{ secrets.ACR_CREDENTIALS }}' | jq -r .password)" >> $GITHUB_OUTPUT
          echo "loginServer=$(echo '${{ secrets.ACR_CREDENTIALS }}' | jq -r .loginServer)" >> $GITHUB_OUTPUT

    - name: Login to Azure Container Registry
      run: echo "${{ steps.acr.outputs.password }}" | docker login ${{ steps.acr.outputs.loginServer }} -u ${{ steps.acr.outputs.username }} --password-stdin


    #- name: Login to ACR
    #  run: az acr login --name dockerregistryt432163

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    #- name: Docker login
    #  run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login dockerregistryt432163.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    # - name: login to Azure Container Registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: dockerregistryt432163.azurecr.io
    #     username: ${{ secrets.REGISTRY_USERNAME }}
    #     password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Extract Metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: dockerregistryt432163.azurecr.io/my-nodejs-app
        tags: |
          latest
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4    
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
  