name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Run unit tests
      run: npm run test

    - name: Run security audit
      run: npm audit --audit-level=moderate

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: "Login to Azure Container Registry"
      run: az acr login --name dockerregistryt432163 
      with:
        login-server: dockerregistryt432163.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t dockerregistryt432163.azurecr.io/my-nodejs-app:latest .
        docker push dockerregistryt432163.azurecr.io/my-nodejs-app:latest