name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v5.0.0
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: "Building command"
      run: npm run build 
    - name: "Running Unit Tests"
      run: npm run test 

    - name: "Running Security Checks"
      run: npm audit --audit-level=moderate 

    - name: "Building Docker Image"
      run: docker build -t my-nodejs-app:latest .
    

    - name: Cleanup Trivy Environment File
      run: |
        if [ -f trivy_envs.txt ]; then
        rm -f trivy_envs.txt
        fi


    - name: "Trivy Scan for Docker Image"
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
         image-ref: my-nodejs-app:latest
         format: 'table'
         exit-code: '1'
         severity: 'CRITICAL,HIGH'
         ignore-unfixed: true
         vuln-type: 'os,library'

    - name: Save Docker image as artifact
      run: docker save my-nodejs-app:latest -o myapp.tar
    - name: Upload Docker Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: myapp.tar
    