name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v5.0.0
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: "Building command"
      run: npm run build 
    - name: "Running Unit Tests"
      run: npm run test 

    - name: "Running Security Checks"
      run: npm audit --audit-level=moderate 

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURECREDENTIALS }}    

    - name: "Login to Azure Container Registry"
      run: az acr login --name dockerregistryt432163 
      witht:
        - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: mycontainer.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t mycontainer.azurecr.io/myapp:${{ github.sha }}
        docker push mycontainer.azurecr.io/myapp:${{ github.sha }}  

    - name: "Building Docker Image"
      run: docker build -t my-nodejs-app:latest .
    
    - name: Push to Azure Container Registry
      run: |
        az acr login --name dockerregistryt432163
        docker tag my-nodejs-app:latest dockerregistryt432163.azurecr.io/my-nodejs-app:latest
        docker push dockerregistryt432163.azurecr.io/my-nodejs-app:latest
